#!/usr/bin/env bash
set -e

/data/code_0.sh &
/data/code_1.sh &
/data/code_2.sh &
/data/code_3.sh &
/data/code_4.sh &
/data/code_5.sh &
/data/code_6.sh &
/data/code_7.sh &
/data/code_8.sh &
/data/code_9.sh &
/data/code_10.sh &
/data/code_11.sh &
/data/code_12.sh &
/data/code_13.sh &
/data/code_14.sh &
/data/code_16.sh &
/data/code_17.sh &
/data/code_18.sh &
/data/code_19.sh &
/data/code_20.sh &
/data/code_21.sh &
/data/code_22.sh &
/data/code_23.sh &
/data/code_24.sh &
/data/code_25.sh &
/data/code_26.sh &
/data/code_27.sh &
/data/code_28.sh &
/data/code_29.sh &
/data/code_30.sh &
/data/code_31.sh &
/data/code_32.sh &
/data/code_33.sh &
/data/code_34.sh &
/data/code_35.sh &
/data/code_36.sh &
/data/code_37.sh &
/data/code_38.sh &
/data/code_39.sh &
/data/code_40.sh &
/data/code_41.sh &
/data/code_42.sh &
/data/code_43.sh &
/data/code_44.sh &
/data/code_45.sh &
/data/code_46.sh &
/data/code_47.sh &
/data/code_48.sh &
/data/code_49.sh &
/data/code_15.py &

tail -f /dev/null
